import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SignUp extends JFrame {

    public SignUp() {
        super("SignUp Form");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(300, 250);
        this.setLayout(new BorderLayout());

        // Create a panel for the signup form
        JPanel signupPanel = new JPanel();
        signupPanel.setLayout(new GridBagLayout());
        signupPanel.setBorder(BorderFactory.createTitledBorder("Signup"));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);

        // Email field
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.LINE_END;
        signupPanel.add(new JLabel("Email Address"), gbc);

        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.LINE_START;
        JTextField emailField = new JTextField(15);
        signupPanel.add(emailField, gbc);

        // Password field
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.LINE_END;
        signupPanel.add(new JLabel("Password"), gbc);

        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.LINE_START;
        JPasswordField passwordField = new JPasswordField(15);
        signupPanel.add(passwordField, gbc);

        // Forget Password link
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        JButton forgetPasswordButton = new JButton("Forget Password");
        forgetPasswordButton.addActionListener(new ActionListener() { //ActionListener() : used to handle events generated by GUI components such as buttons, text fields, and menus. 
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(SignUp.this, "Please contact support to reset your password.");
            }
        });
        signupPanel.add(forgetPasswordButton, gbc);

        // Login button
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        JButton loginButton = new JButton("Login");
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String email = emailField.getText();
                String password = new String(passwordField.getPassword());
                if (!email.isEmpty() && !password.isEmpty()) {
                    // Here you would typically validate the credentials against a database or API
                    JOptionPane.showMessageDialog(SignUp.this, "You have logged in successfully.");
                } else {
                    JOptionPane.showMessageDialog(SignUp.this, "Please enter both email and password.", "Invalid Credentials", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        signupPanel.add(loginButton, gbc);

        this.add(signupPanel, BorderLayout.CENTER);
        this.setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignUp();
            }
        });
    }
}

